### ISSUE TITLE
Data Sync to QA environment

### ISSUE THREAD

**Issue by gamontoya** [ucsdlib/damspas#679]
### Descriptive summary

- Data sync needed from prod to QA. This should include everything (triplestore, solr, files, etc.)

### Needed for 

- [ ] Enforce _created_ and _modfied_ dates https://github.com/ucsdlib/damsrepo/issues/92

**Comment by jgorney** [comment]
Will do!

**Comment by gamontoya** [comment]
@jgorney Please wait until Matt or Longshou request it.

**Comment by gamontoya** [comment]
@mcritchlow Please ping Juliana or Ron when you're ready.

**Comment by gamontoya** [comment]
Kamino cloned this issue to [ucsdlib/damspas](https://github.com/ucsdlib/damspas/issues/680)

**Comment by mcritchlow** [comment]
@lsitu - correct me if I'm wrong, but I don't see any reason not to start sync to QA now. We still need to work on our code a bit to get ready for the full solr reindex, but I think we could start the DB/file sync now?

**Comment by gamontoya** [comment]
@mcritchlow Got it! 

@jgorney Feel free to start this when you have time.

**Comment by rstanonik** [comment]
I'll start it today, but depending on how much production has changed since the last sync, this could take days..  I'll have a better estimate after it has run a while.

**Comment by gamontoya** [comment]
@rstanonik I'll be interested to know how it goes. Last time you did a data sync to staging and QA it took one day only.

**Comment by jgorney** [comment]
Starting the DB prod to QA part now.  

Just to confirm - the sync to staging is to start Monday?

**Comment by gamontoya** [comment]
@jgorney Matt said to start now.

**Comment by gamontoya** [comment]
@jgorney Looks like @rstanonik started already?

**Comment by jgorney** [comment]
@gamontoya start both syncs now?  I just started prod -> QA.  We should also start prod -> staging?

**Comment by gamontoya** [comment]
@jgorney No, just this ticket. I opened the prod to staging ticket but I have not assigned it to Ops yet. I'm waiting to hear from other folks before I make the request.

**Comment by jgorney** [comment]
The prod DAMS db triplestore sync to QA is complete.

**Comment by rstanonik** [comment]
The file sync is 2% done in about 1/2 hour, so estimate 25 hours to complete.  I'll check on it occasionally to see if that changes much.

The solr sync is done.

**Comment by mcritchlow** [comment]
thanks all!

**Comment by rstanonik** [comment]
After about 4 hours, about 9% done, so estimate 44 hours.
Progress slowed because of 2.2T object (bb0891487n).
Progress might increase if remaining new objects are smaller.

**Comment by rstanonik** [comment]
62% done in 21 hours, so estimate another 13 hours.

**Comment by mcritchlow** [comment]
ok, thanks for the heads up @rstanonik . @lsitu and i will try and get things as ready as we can today to start testing tomorrow

**Comment by lsitu** [comment]
@mcritchlow Sounds good. Do we need a release ticket for damsrepo now or later after we testing it?

**Comment by mcritchlow** [comment]
@lsitu - i'm thinking we deploy damsrepo and my damspas branch for testing first. then do releases once we know it's in good shape. does that sound good? i'm waiting to deploy my branch to QA because @VivianChu has a branch deployed for @gamontoya to test. Once they're done, I'll deploy mine. I think that'll set us up if we get damsrepo deployed today as well.

**Comment by lsitu** [comment]
@mcritchlow Yes, that sounds good to me.

**Comment by gamontoya** [comment]
@mcritchlow I have finished my QA work with @VivianChu . Feel free to proceed.

**Comment by rstanonik** [comment]
file sync finished last night (Jul 11 21:22).  Started Jul 10 around 11:30, so about 34 hours total.

**Comment by mcritchlow** [comment]
@rstanonik - thank you!

@lsitu - so i think we need to get damsreo deployed to QA and start a full reindex, does that sound like the next step to you?

I can deploy my branch to QA whenever we're ready for testing via damspas.

**Comment by lsitu** [comment]
@mcritchlow I've deployed damsrepo to staging. I'll reindex all records after damsolrizer is restarted. 
@rsanonik I can restart damsolrizer on QA through Jenkins. It's stalled there. Could you take a look? Thanks.

**Comment by rstanonik** [comment]
I started damsolrizer on QA.  I'm looking at the Jenkins plan.

**Comment by rstanonik** [comment]
Jenkins plan now seems to work

**Comment by lsitu** [comment]
@rstanonik I see two consumers are running there: http://lib-hydratail-qa.ucsd.edu:8161/admin/queues.jsp. We should have only one consumer. Maybe the place failed to kill the existing stalled solrizer?

**Comment by rstanonik** [comment]
Where should solrizer run? 
On hydratail or hydrahead?
I guess I forgot that QA runs it on hydratail.
I created jenkins to start it on hydrahead.
Let me know when it should run and I change jenkins to do that.

staging and prod run it on hydrahead.

**Comment by rstanonik** [comment]
Okay, I see that solrizer is commented out on QA hydrahead at boot.

I'll change jenkins to restart solrizer on QA hydratail

**Comment by rstanonik** [comment]
jenkins now restarts solrizer on QA hydratail.

I ran it just now

**Comment by lsitu** [comment]
@rstanonik Thanks. The solrizer seems to be running but SOLR is broken. I got error `java.lang.IllegalArgumentException: All checkers need to use the same Analyzer.` while access solr: http://lib-hydratail-qa.ucsd.edu:8983/solr/blacklight/select?q=*:*
Is SOLR configuration messing up, or we just need a restart? Thanks.

**Comment by rstanonik** [comment]
QA solr did seem to have a problem.
I restarted it.
Let me know if that helps

**Comment by rstanonik** [comment]
QA DAMS still isn't responding

**Comment by rstanonik** [comment]
It did finally respond

**Comment by lsitu** [comment]
@rstanonik I am still getting the error from SOLR on QA:
http://lib-hydratail-qa.ucsd.edu:8983/solr/#/blacklight/query
```
{
  "responseHeader": {
    "status": 500,
    "QTime": 1,
    "params": {
      "q": "*:*",
      "indent": "true",
      "wt": "json",
      "_": "1563202461859"
    }
  },
  "error": {
    "msg": "All checkers need to use the same Analyzer.",
    "trace": "java.lang.IllegalArgumentException: All checkers need to use the same Analyzer.\n\tat org.apache.solr.spelling.ConjunctionSolrSpellChecker.addChecker(ConjunctionSolrSpellChecker.java:79)\n\tat org.apache.solr.handler.component.SpellCheckComponent.getSpellChecker(SpellCheckComponent.java:606)\n\tat org.apache.solr.handler.component.SpellCheckComponent.prepare(SpellCheckComponent.java:129)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:246)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:2082)\n\tat org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:670)\n\tat org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:458)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:225)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:183)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:499)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)\n\tat java.lang.Thread.run(Thread.java:745)\n",
    "code": 500
  }
}
```

**Comment by rstanonik** [comment]
The solrconfig seems to have spellcheck, which might be the problem, it's different from staging and prod which have spellcheck false.  I'm trying to figure out why qa is different.

**Comment by rstanonik** [comment]
During the solr sync, I must have copied an old solrconfig, which still contained spellcheck.  I ran the jenkins plan to deploy the solr config, after which the query correctly returns data.  Then I did another solr sync and confirmed the solrconfig doesn't contain spellcheck and the query correctly returns data.

Please try now.

**Comment by lsitu** [comment]
@rstanonik Thanks. SOLR on QA works now. But solrizer is down and I can't restart it from Jenkin. The build is stalled there with yellow status.
Could we restart ActiveMQ and the Solrizer so that we can start a new round of clean full solr indexing? Thanks.

**Comment by rstanonik** [comment]
I started solrizer and restarted activemq.
Try now

**Comment by lsitu** [comment]
@rstanonik It looks like damsolrizer failed to be restarted. I see no consumers in ActiveMQ: http://lib-hydratail-qa.ucsd.edu:8161/admin/queues.jsp.

**Comment by rstanonik** [comment]
I restarted solrizer and it is running.
Maybe last time I restarted activemq after solrizer and brief loss of activemq killed solrizer.
Order might be important.

**Comment by lsitu** [comment]
@rstanonik I see 4 consumers running now: http://lib-hydratail-qa.ucsd.edu:8161/admin/queues.jsp. It look like the Jenkin's plan just start damsolrize without killing the existing processes. Could you take a look again. Thanks.

**Comment by rstanonik** [comment]
I'm sorry.
There was a problem with the sorlizer script, which I tried to fix, but made worse.
Please try now.

**Comment by lsitu** [comment]
@rstanonik I think it's working now and I see objects are updated in SOLR on QA. Thanks.

**Comment by rstanonik** [comment]
I think part of the confusion is that QA runs solrizer on hydratail, but damspas deploys to hydrahead and starts solrizer there.  Maybe QA can move solrizer to hydrahead, like staging and production.  I don't remember why QA solrizer is on hydratail.

**Comment by mcritchlow** [comment]
@rstanonik - oh that's a great find. I don't recall historically why QA runs damsolrizer on hydratail, feels like an artifact of some architectural experiments we did years ago. Either way, unless @lsitu knows of a reason solrizer needs to be on hydratail, I'm definitely in favor of aligning the damsolrizer location across environments. Presumably, we could then have the Jenkins plan call the same shell script that damspas does on deploys now?

**Comment by lsitu** [comment]
@mcritchlow / @rstanonik I don't recall that we have any reasons to make QA run damsolrizer differently. think it's good to make it consistent with other environments. Thanks.

**Comment by lsitu** [comment]
@rstanonik It looks like damsolrizer on QA is in troble again and I am seeing two consumers running at ActiveMQ at the same time. I tried to restart it with the Jenkin plan it it stalled there with yellow status. Could you take a look? Thanks.

**Comment by lsitu** [comment]
@rstanonik Have you got a chance to look at damsolrizer on QA? I am able to restart it with the Jenkins plan now but there are still 2 consumers there. Thanks.

**Comment by rstanonik** [comment]
This is puzzling.
On lib-hydratail-qa (where activemq runs) there are two ESTABLISHED connections
[root@lib-hydratail-qa conf]# netstat -tn | grep 61613
tcp        0      0 132.239.119.78:61613        1232.39.119.77:44106        ESTABLISHED
tcp        0      0 132.239.119.78:61613        132.239.119.77:41316        ESTABLISHED

both from lib-hydrahead-qa (1232.39.119.77)

But on lib-hydrahead-qa, there is only one ESTABLISHED connection
[root@lib-hydrahead-qa ~]# netstat -tn | grep 61613
tcp        0      0 132.239.119.77:41316        132.239.119.78:61613        ESTABLISHED

It's as if activemq is configured to not timeout connections, so it doesn't detect that one of the connections has been closed.

I'm trying to understand why this is happening.

**Comment by rstanonik** [comment]
By the way, there is only one damsolrizer running on lib-hydrahead-qa, this time.

**Comment by rstanonik** [comment]
Also by the way, QA damspas probably isn't working because
APPS_DHH_QA_SOLR_URL='http://lib-hydrahead-qa.ucsd.edu:8983/solr/blacklight'

solr is now on lib-hydratail-qa

**Comment by mcritchlow** [comment]
@jhriv - I think we have that issue sorted out with the env-variables PRs that you merged yesterday. perhaps we need a redeploy?

**Comment by rstanonik** [comment]
APPS_DHH_QA_SOLR_URL is fixed now.  damspas has been restarted and damsolrizer has been restarted.  lib-hydratail-qa still thinks there are two connections, but there is only one solrizer

**Comment by rstanonik** [comment]
I don't know why activemq thinks there are two consumers.  There is only one damsolrizer and only one connection from lib-hydrahead-qa.  I'd like to restart activemq and then restart damsolrizer.

**Comment by lsitu** [comment]
@rsanonik It's interesting. I am still seeing two damssolrizer consumers. Have you restarted activemq and then restart damsolrizer?

**Comment by rstanonik** [comment]
After I restated activemq, there were no connections. 
After I restarted damsolrizer (jenkins plan)r, there is one connection.
Then I restarted damsolrizer again (jenkins plan) and there is one damsolrizer and one connection.

**Comment by lsitu** [comment]
Thanks @rstanonik. I just tried and it's working. I'll try another round of full solr index again.
